spring: 
  profiles:
    active: dev

logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/springcloud-turbine
  
---
spring:
  profiles: dev
  application:
    name: trubine
    
server:
  port: 9003
  
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: turbine-01
    prefer-ip-address: true
    
turbine:
  appConfig: consumer
  clusterNameExpression: new String("default")
  combine-host-port: true